### ISSUE TITLE
No LXC Objects visible in UI

### ISSUE THREAD

**Issue by seffyroff** [AdaptiveScale/lxdui#125]
Hi there,

Thanks so much for releasing this tool - it shows real promise!

I'm up and running after following your install docs, however the UI doesn't seem to be picking up any of my LXC setup from the host - looking at the containers page, the container already running on the host is not listed.  If I try to create a new container, the UI complains no Storage Pools are available (there are 2 created on the host and visible if I lxc storage list).

I imagine I've made some basic faux pas here, can you point me in the right direction please?

**Comment by vhajdari** [comment]
Hi @seffyroff, 

Make sure you've gone through the `lxd init` process and set the desired options (or take all the defaults).  Once LXD is configured, I'd advise logging out of your sessions and logging back in.  Depending on the installation path you took you can start LXDUI by typing `lui start &`, that is if you installed it globally and not in a vitualenv, or from the directory where you cloned the project with `python3 run.py start &`.  If you installed in a virtualenv then make sure you source your `venv` once you log back into your session.  If you can interact with LXD from the CLI with the `lxc` client then you should be all set to use UI.  LXDUI will connect to the local unix socket to communicate with the LXD daemon and allow you to manage your containers for that host.

**Comment by seffyroff** [comment]
Thanks @vhajdari for the rapid response 👍 
I ran through your docs first via a venv and then without to see if that would make a difference.  Running LXD init a second time (it was still configured from the previous time so that's why I now have two storage pools).  
eg:
```
$ lxc storage ls
+----------------+-------------+--------+---------------------------------------+---------+
|      NAME      | DESCRIPTION | DRIVER |                SOURCE                 | USED BY |
+----------------+-------------+--------+---------------------------------------+---------+
| default        |             | dir    | /var/lib/lxd/storage-pools/default    | 0       |
+----------------+-------------+--------+---------------------------------------+---------+
| default-rombus |             | zfs    | /var/lib/lxd/disks/default-rombus.img | 3       |
+----------------+-------------+--------+---------------------------------------+---------+
```
and..
```
$ lxc ls
+-------------------+---------+---------------------+----------------------------------------------+------------+-----------+|       NAME        |  STATE  |        IPV4         |                     IPV6                     |    TYPE    | SNAPSHOTS |
+-------------------+---------+---------------------+----------------------------------------------+------------+-----------+| advanced-cardinal | RUNNING | 10.56.169.35 (eth0) | fd42:a5ee:f9f:ab34:216:3eff:feb8:8819 (eth0) | PERSISTENT | 0         |
+-------------------+---------+---------------------+----------------------------------------------+------------+-----------+
```
But there are no running containers in lxdui: (the network panel is similarly barren)
![lxdui](https://user-images.githubusercontent.com/8338529/39451334-30553536-4c83-11e8-989e-d25d7f622660.PNG)
and I see an error when I try to spin one up:
![lxdui2](https://user-images.githubusercontent.com/8338529/39451349-40582916-4c83-11e8-9318-268d50268e02.PNG)

**Comment by seffyroff** [comment]
Continuing to try and resolve this myself, no luck.  I realised I'd not chosen all defaults for lxd init, (I opted to enable access to lxd over network, which I wondered if it disabled the unix socket in favor of some tcp socket instead) so I manually removed all profiles, networks, storage, images and containers, then snap remove lxd, then logout/in and snap install lxd, ran lxd init accepting ALL defaults this time, then did lui stop, lui init, lui start, and still seeing the same issue.

I tried the same thing on another host, and managed to get lxdui working, so perhaps the issue is one of the host OS - the working one is on Ubuntu Xenial, the not working ones are on Bionic.  Both have 3.00 of xld installed by snap, so something else Bionic is doing is causing trouble I guess.  I'll see if I can find more out.

**Comment by vhajdari** [comment]
I'll have to test it on Bionic to see it there are any quirks to be worked and provide feedback accordingly.

**Comment by vhajdari** [comment]
@seffyroff, looks like you got further than me on Bionic.  I just did a clean install of Bionic Desktop with a fresh install of LXD `snap install lxd` .  I can't even get past `lxd init`.  I'm stuck at `Failed to connect to local LXD ... permission denied.` . 

Are you seeing any error messages in the console?
