### ISSUE TITLE
<Feature Request> Port Management

### ISSUE THREAD

**Issue by Meywether** [AdaptiveScale/lxdui#159]
Dear programmers,
thanks for this great project. 
Would it be possible to add a port-forwarding possibility?

So external ports <-> internal ports can be graphical maintained which are currently used by LXD containers? 

Thanks in advance for your response and your awesome project!

Best regards
Meywether

**Comment by vhajdari** [comment]
Thanks for the request @Meywether.  We'll add it to our list.

One clarifying question.  
Do you intend to specify the ports you are exposing in the container though a configuration setting or do you want to specify it upon invocation?

**Comment by lcherone** [comment]
This can be done with a proxy device: https://github.com/lxc/lxd/blob/master/doc/containers.md#type-proxy 

Added to [Conext](https://github.com/lcherone/Conext) this morning ;p

**Comment by Meywether** [comment]
Thanks for mentioning!

**Comment by vhajdari** [comment]
Feature added in the latest release of 2.1.2
![image](https://user-images.githubusercontent.com/11463491/42828193-ca4b2486-89ad-11e8-85e3-ce616f83eab9.png)
