### ISSUE TITLE
running lxdui says:  LXDUI started. Running on http://0.0.0.0:15151

### ISSUE THREAD

**Issue by bmullan** [AdaptiveScale/lxdui#160]
Ubuntu 18.04...  SNAP LXD ....

bmullan@bmullan:~/lxdui$ **python3 run.py start**
LXDUI ver. 2.0 -- (c)AdaptiveScale, Inc.
http://www.adaptivescale.com
LXDUI started. Running on **http://0.0.0.0:15151**
PID=2376, Press CTRL+C to quit

Why is it picking **0.0.0.0** ?

**Comment by bmullan** [comment]
Thx for explanation..

**Comment by roman-kozin** [comment]
Hi.
Can i replace listen network interface? I want that lxdui, to listen loopback interface only.

**Comment by vhajdari** [comment]
@roman-kozin you can modify the startup python and replace 0.0.0.0 with 127.0.0.1
