### ISSUE TITLE
RaspberryPi compatibility

### ISSUE THREAD

**Issue by frenchfaso** [AdaptiveScale/lxdui#163]
Hello there,
I have lxd running on a Pi3 and would like to try your sweet webGui, but when I run the install script (in a venv) I get the following error:
``unable to execute 'arm-linux-gnueabihf-gcc': No such file or directory
error: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1``
I suppose it's trying to cross-compile something for the arm, but it is already running on an arm, so it should probably call directly gcc.
Is there something I can easily change in the install script to make it run on the Pi3?
Thanks for your help and for pushing your work in the open!

**Comment by vhajdari** [comment]
Hi @frenchfaso,

I have not tested LXDUI on a RPi yet, but I'm guessing if you can compile the libs into ARM then the UI should work just fine.  You will need the build tools for that processor.  

try these steps:
```
######> Setup Script ######
sudo apt-get purge lxd lxd-client -y
sudo apt install -y git libssl-dev build-essential python3-dev python3-pip python3-venv zfsutils-linux bridge-utils
sudo snap install lxd
lxd init --auto
git clone https://github.com/AdaptiveScale/lxdui.git
cd lxdui
deactivate
python3 -m venv venv1
source venv1/bin/activate
pip3 install pip --upgrade
pip3 install requests==2.9.1
pip3 install -r requirements.txt
python3 setup.py install
###### Setup Script <######```
