### ISSUE TITLE
Setup scripts fails on vanilla Ubuntu 16.04 LTS install

### ISSUE THREAD

**Issue by tsener** [AdaptiveScale/lxdui#173]
setup.py fails with the following:
root@lxc-l-01a:/opt/lxdui# python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'
---------------

root@lxc-l-01a:/opt/lxdui# uname -a
Linux lxc-l-01a 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@lxc-l-01a:/opt/lxdui# python3 -V
Python 3.5.2

**Comment by Meywether** [comment]
Hi tsener,
the error message said that a package named "setuptools" was not found.

Have you tried installing the package: setuptools by using `apt install python3-setuptools` ?

Kind regards
Meywether

>

**Comment by vhajdari** [comment]
@tsener, were you able t get past this issue?  Let us know if you need further assistance.

**Comment by ailegion** [comment]
issue will be closed as it could not be replicated
