### ISSUE TITLE
Properly enabling TLS/HTTPS

### ISSUE THREAD

**Issue by unquietwiki** [AdaptiveScale/lxdui#2]
http://flask.pocoo.org/snippets/111/

I was able to change the main file, with the ssl_context of the last comment in that linked thread. I surmise one could add an optional command line; or extra lines in config.json; to not have to recompile the program when wanting to use TLS certs.

**Comment by ydf** [comment]
please  use  uwsgi  and  nginx , its  very simple

**Comment by ydf** [comment]
pip install uwsgi
cd  /opt/lxdui/lxdui  && uwsgi --http-socket 127.0.0.1:$PORT -M -p 4 -R 3000 -M  -w "app:app" --daemonize $LOG_PATH --log-maxsize 50000000
===========================
nginx set
server {
        listen       80;
        listen 443 ssl http2;
        ssl_session_cache shared:SSL:30m;
        ssl_session_timeout 48h;
        ssl_certificate /opt/ssltools/chained.pem;
        ssl_certificate_key /opt/ssltools/domain.key;
        ssl_stapling on;
        ssl_stapling_verify on;
        server_name  lxdui.local;


        location / {
            client_max_body_size 100m;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://127.0.0.1:8888;
        }
}

**Comment by unquietwiki** [comment]
Thanks @ydf : I think I was trying what you did here with Caddy, but no luck for some reason. My current setup is more of a test, but I figure your solution does solve the problem!
