### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by ktechmidas** [AdaptiveScale/lxdui#206]
Hi guys,

I noticed a lack of port forwarding options in lxdui, I have a simple Python script I use for it that modifies iptables. There doesn't seem to be anything better for it right now,  so would you guys have any objection to me doing a pull request with the iptables script + some UI stuff for it? (Plus make it optional, so it doesn't have to be used)

I thought I would ask first, as some projects don't really like to touch low-level things like iptables

**Comment by vhajdari** [comment]
Hi @ktechmidas,

We have port forwarding/mapping on the roadmap, but it's still a few revs out.  We'd love to have your contribution for port mapping, and we can include this in the `bin` directory with other tools/helper scripts.  

Add your script in `bin` and create a PR.  Once reviewed and tested we'll add it in to an upcoming release.

From a UI perspective there will be a way to do port mappings visually, and we'll leverage a device configuration for this.  LXD has a nifty way of handling devices and allows us to use the native API with the proxy device for this.

If you want to create port mappings natively with lxc you can use something like this:
`lxc config device add c1 enp0s8 proxy listen=tcp:172.16.1.102:80 connect=tcp:10.172.49.141:8888`

here's a quick rundown of what this command is doing:
```
c1 = the name of the container
enp0s8 = ethernet interface on the LXD host
172.16.1.102:80 = the ip and port i want to listen for connections on
10.172.49.141:8888 = the container's ip and port where i want to send the tcp traffic to
```

Take a look here: https://github.com/lxc/lxd/blob/master/doc/containers.md#type-proxy
lxc config device add <container> <device-name> proxy listen=<type>:<addr>:<port>[-<port>][,<port>] connect=<type>:<addr>:<port> bind=<host/container>

**Comment by vhajdari** [comment]
Version 2.1.2 has just been released with the port mapping feature.  Please got it a try and let us know what you think.

![image](https://user-images.githubusercontent.com/11463491/42828044-6d965652-89ad-11e8-97e5-d414839e3ba2.png)

**Comment by ktechmidas** [comment]
Thanks for coming back to me @vhajdari ! Sorry I didn't get the time to clean up my utility script... I will update tomorrow and check it out, this will really help us 👍
