### ISSUE TITLE
LXDUI development

### ISSUE THREAD

**Issue by ghoshanjega** [AdaptiveScale/lxdui#237]
Thanks team for the great UI solution to manage LXD.

I would like to modify some features and adapt to my use case. But I cannot produce a development server due to my inexperience in flask and flask-cli interface.

How do I fork this repo to setup in a dev environment where changes in code is recognized on browser refresh. Setting debug gives me "RuntimeError: There is no current event loop in thread 'Thread-1'."

**Comment by vhajdari** [comment]
Hi @ghoshanjega ,

If you intend to just make some changes to test out your use case you do not need to create a fork.  Just work with the code from the cloned repo.  In case you want to contribute those changes back then you should create a fork on GitHub (you can find plenty of instructions on GitHub for this), do your work on this fork, and then create a PR.  Hope this helps.

**Comment by ghoshanjega** [comment]
Hi @vhajdari 

Thanks. I have cloned. My issue is that I would like a development server. "lxdui start" runs a production server where I think it runs off a build. 

I would like to access the core flask app. "flask run" and changes to the code shows on browser reload.

**Comment by ghoshanjega** [comment]
Closing this issue as it was my Google Chrome acting up with heavy caching.
