### ISSUE TITLE
password change

### ISSUE THREAD

**Issue by angryvincent** [AdaptiveScale/lxdui#240]
default user and password is admin/admin. Is there ability to change and where?

**Comment by angryvincent** [comment]
it is in lxdui user add -u user -p passwd
Can be closed. Sorry for the noise

**Comment by vinyll** [comment]
Running `lxdui user update -u admin` says :

```
Password:
Repeat for confirmation:
Change user password
```

However the default "admin" password still works and the new one does not.

Same for `lxdui user update -u admin -p mynewpassword`

**Comment by vhajdari** [comment]
Check they auth.conf file.  When the password is changes this file is updated with the new password hash.  It the file is not being updated it might be a permission issue.

**Comment by vinyll** [comment]
Right, I'm confused then…

```
(venv) ubuntu@ubuntu:~/lxdui$ lxdui user list
User Accounts:
1. admin
2. ubuntu
(venv) ubuntu@ubuntu:~/lxdui$ cat conf/auth.conf
[
  {
    "password": "d033e22ae348aeb5660fc2140aec35850c4da997",
    "username": "admin"
  }
]
```

It feels like this file is the one used by the web ui but not used with the command line.

**Comment by vinyll** [comment]
Oh, you know what?
Running `python3 run.py start` reads different than `lxdui start`…

Using `lxdui start` reads from the config connected with the CLI.
Not sure where the file stores, but it will do for now.

:)
