### ISSUE TITLE
Login form and disabled JavaScript

### ISSUE THREAD

**Issue by number0** [AdaptiveScale/lxdui#253]
Go to login page 
Disable JavaScript 
Enter any text as username and password 
Access Granted

tested on LXDUI v2.1.2

**Comment by vhajdari** [comment]
Hi @number0 

Once you are on the UI (after access granted), are you able to navigate through the UI or execute any actions?

**Comment by vhajdari** [comment]
@ailegion this is a top priority bug-fix.

After disabling JavaScript the system can't be modified in any way, but all data at the top hierarchy (page) is readable.
