### ISSUE TITLE
Terminal emulator not working

### ISSUE THREAD

**Issue by w1bsb** [AdaptiveScale/lxdui#257]
Running Debian 9.5 with lxd installed via snap.  Installed both master and development branch, no errors reported. Everything appears to work except the "terminal" emulator when I try to open a terminal for a container. I get the new browser tab, and a black screen with a blinking cursor but it never shows anything. I am able to access the container using the command line and opening a bash shell to it, or with ssh once installed inside the container.

**Comment by vhajdari** [comment]
Hi @w1bsb 

I have not tried it on Debian so I can't say its on OS specific issue/bug.  Have you had a chance to try it out on Ubuntu 16 or 18 as a comparison?  Are there any errors in the log that you can share?

**Comment by jslarraz** [comment]
Some here on Ubuntu 18, this is the log report

  File "/usr/local/lib/python3.6/dist-packages/terminado-0.8.1-py3.6.egg/terminado/websocket.py", line 54, in open
    self.terminal = self.term_manager.get_terminal(url_component)
  File "/usr/local/lib/python3.6/dist-packages/LXDUI-2.1.2-py3.6.egg/app/lib/termmanager.py", line 30, in get_terminal
    term = self.new_terminal(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/terminado-0.8.1-py3.6.egg/terminado/management.py", line 171, in new_terminal
    pty = PtyProcessUnicode.spawn(argv, env=env, cwd=options.get('cwd', None))
  File "/usr/local/lib/python3.6/dist-packages/ptyprocess-0.6.0-py3.6.egg/ptyprocess/ptyprocess.py", line 203, in spawn
    raise TypeError("Expected a list or tuple for argv, got %r" % argv)
TypeError: Expected a list or tuple for argv, got None
2019-02-05 12:27.48 - terminado.websocket - INFO - Websocket closed

**Comment by AlexanderPlaza** [comment]
I just receive a black terminal window that opens up in a new tab. Just a blinking cursor and I unable to do any input.

Any advice how I can find the logs or how to correct this issue?

**Comment by dariuscardren** [comment]
I came a crossed this post looking into the same issue on ubuntu 18.04 using the snap version of lxd

**Comment by a0s** [comment]
Terminal window is working when lxdui started on raw system
Terminal window is not working when lxdui started inside docker container with -p 15151:15151.
Terminal window is not working even when lxdui started inside docker container with --net=host.

**Comment by vhajdari** [comment]
The reason that it works sometimes and not others is that in the argument
for the shell executable is set to a static value.  Depending on the
container it may or may not have the shell environment that terminal app is
expecting.  If you install Bash inside of your container you should be able
to use it then.  Give that a try and let us know how you make out.

Regards,

Tony Hajdari
