### ISSUE TITLE
Remote access web UI?

### ISSUE THREAD

**Issue by fahdr** [AdaptiveScale/lxdui#261]
How can I  run this ui from a remote machine?
ie Access server on cloud from laptop

**Comment by vhajdari** [comment]
Hi @fahdr,

The easiest way to accomplish this is to collocate LXDUI with your LXD instance in the cloud, and open up a firewall port to the running instance--this is configurable in the conf file if you want to select a custom port.  The UI would then be accessed over the public internet.
