### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by newdee** [AdaptiveScale/lxdui#262]
LXD Version: 3.7
When I  launched new container from my own image, I could not open the terminal from lxdui page, it just shows:
```
500: Internal Server Error
```
And I use Ubuntu:16.04 image to create container,  it can open terminal from lxdui page first, but it shows black page after a while.
How to solve it?
Any help is welcome.

**Comment by vhajdari** [comment]
Hi @newdee,

Do you have any logs from lxdui that you can share so that we can help you troubleshoot your issue?
Is this the case with containers created from other images as well or does it only affect containers created from your images?

**Comment by vhajdari** [comment]
Hi @newdee,

I suspect you may be running into a timeout condition when the JWT token expires -- `lxdui.jwt.token.expiration = 1200` 
Can you validate if this is case?

**Comment by intrepidsilence** [comment]
I wondered if that was what it was talking about.  This is what I did and I can now open a Terminal:

`lxc config set <CONTAINER> image.os ubuntu`
`lxc config set <CONTAINER> image.release bionic`

Thanks @ailegion !

**Comment by intrepidsilence** [comment]
I had another thought on this.  This problem occurred when I created a new image from a container using export.  You ovviously cannot control the creation of images outside of the UI but inside it you could copy the os and release from the container it is coming from.

**Comment by ailegion** [comment]
@mineibrm let's have a look at this and see if we can fix and close this

**Comment by jetroni** [comment]
A default shell type was added way before in case there is no configuration set for 'image.os'.

https://github.com/AdaptiveScale/lxdui/blob/48e1e0689c00da42b25e8968be5dfad0f8c57741/app/api/controllers/terminal.py#L25-L30
