### ISSUE TITLE
lxdui CLI problems

### ISSUE THREAD

**Issue by Rico29** [AdaptiveScale/lxdui#263]
Hello,
New to lxdui, I'm trying to configure it. Tried to enable SSL with my own certificates : 
```
root@LXC-1:~# lxdui cert add -c /etc/ssl/certs/adm.celya.fr.crt -k /etc/ssl/private/adm.celya.fr.key 
root@LXC-1:~# lxdui config show | grep ^lxdui.ssl
lxdui.ssl.cert = /etc/ssl/certs/adm.celya.fr.crt
lxdui.ssl.key = /etc/ssl/private/adm.celya.fr.key
root@LXC-1:~# lxdui cert list
root@LXC-1:~#
```
I also tried to run lxcui in background mode without success. (tried `lxdui config set lxdui.mode background`  and things like that...)

Is there an systemd startup script available anywhere ?
Thanks for your help
Regards

**Comment by vhajdari** [comment]
Hi @Rico29 

At the moment there is no systemd startup script available--would be a great addition to the list of contributions.  

To run lxdui in the background you can add the **&** character at the end of the command line `lxdui start &`, or set up [supervisor](http://supervisord.org/).  For example to run lxdui in the background with a quite console you can use: `lxdui start > /dev/null 2>&1`.

The certs feature in lxdui is still experimental, and it primarily exists for custom configurations where you need to connect to multiple LXD servers as a client from lxdui (distributed mode).  If you are trying to run lxdui over HTTPS then I recommend having a look at the following blog -- [Running Your Flask Application Over HTTPS](https://blog.miguelgrinberg.com/post/running-your-flask-application-over-https).

**Comment by Rico29** [comment]
PR for systemd service file : #265

**Comment by vlddm** [comment]
> The certs feature in lxdui is still experimental, and it primarily exists for custom configurations where you need to connect to multiple LXD servers as a client from lxdui (distributed mode). If you are trying to run lxdui over HTTPS then I recommend having a look at the following blog -- [Running Your Flask Application Over HTTPS](https://blog.miguelgrinberg.com/post/running-your-flask-application-over-https).

So how should lxdui be secured to access from the internet? Internal certs is not working, if connection proxied over nginx terminal is not working since its trying to reach https://domain:lxduiport/_websocket that is plain http.

**Comment by vhajdari** [comment]
Hi @vlddm,

Can you elaborate on your use case a bit further?  Are you planning on using SSL certificates from a commercial provider?

BTW, the Internal certs are there only to facilitate connecting the LXDUI client to another LXDUI server other than localhost.  They are not intended to provide a publicly facing service over HTTPS.

In terms of what needs to be done to support HTTPS over a public interface, this is no different than securing any Python Flask app with commercially available certificates.  There is bit of configuration and customization that you'll have to do adjust port numbers and such, and use a reverse proxy that is better suited to the task.

**Comment by vlddm** [comment]
> Hi @vlddm,
> 
> Can you elaborate on your use case a bit further? Are you planning on using SSL certificates from a commercial provider?

Im using letsencrypt certs.
> 
> BTW, the Internal certs are there only to facilitate connecting the LXDUI client to another LXDUI server other than localhost. They are not intended to provide a publicly facing service over HTTPS.
> 
> In terms of what needs to be done to support HTTPS over a public interface, this is no different than securing any Python Flask app with commercially available certificates. There is bit of configuration and customization that you'll have to do adjust port numbers and such, and use a reverse proxy that is better suited to the task.

I need https access to panel via webinterface. Very reasonable idea to have an option not to send plainnext passwords to panel controlling your server with root privileges.
I can terminate https with nginx for sure, but as I mention terminal stop working because it trying to connect to `/_websocket/` directly with wrong scheme.

I have no idea how Flask if working and it would be very nice to have some documentation for this very needed feature.

**Comment by ailegion** [comment]
@vhajdari since currently this change can only be implemented via proxy only I will go ahead and close the issue - we can check back in future
