### ISSUE TITLE
Instructions should be more specific for Python 3 on Debian

### ISSUE THREAD

**Issue by Daniel15** [AdaptiveScale/lxdui#267]
I was following these instructions: https://github.com/AdaptiveScale/lxdui/wiki/Installing-LXDUI-2.0

It says to run `pip install .`. However, on Debian this will use Python 2. You need to `apt install python3-pip` then run `pip3 install .` to use Python 3. It worked fine after I did this.

**Comment by vhajdari** [comment]
Thanks for the update @Daniel15. The Wiki has been updated.
