### ISSUE TITLE
executable file does not appear 

### ISSUE THREAD

**Issue by levin-kelevra** [AdaptiveScale/lxdui#27]
branch: lxdui-2.0
command: sudo python3.5 setup.py install
expectations: sudo lxdui  ... runned
reality: command not found

I think that install_script works incorrect or absent at all.

**Comment by ailegion** [comment]
@levin-kelevra  - @AdaptiveScale-OS and @vhajdari are in process of integrating the setup feature for 2.0. They will update this thread as soon as they are done with testing.

**Comment by vhajdari** [comment]
Branch lxdui-2.0 is under active development and is not ready for release yet.  Once it's ready it will be merged into the master branch.
