### ISSUE TITLE
terminal problem when launching lxdui via systemd

### ISSUE THREAD

**Issue by Rico29** [AdaptiveScale/lxdui#275]
Hello,
I'm facing an issue when launching lxdui via a systemd script : 
```
root@LXC-1:~# cat /lib/systemd/system/lxdui.service 
[Unit]
Description=Web UI for the native Linux container technology LXD/LXC
After=network.target snapd.service
Requires=snapd.service

[Service]
Type=simple
PIDFile=/run/lxdui/lxdui.pid
ExecStart=/usr/local/bin/lxdui start
ExecStop=/usr/local/bin/lxdui stop

[Install]
WantedBy=multi-user.target

root@LXC-1:~# systemctl start lxdui
root@LXC-1:~# systemctl status lxdui
● lxdui.service - Web UI for the native Linux container technology LXD/LXC
   Loaded: loaded (/lib/systemd/system/lxdui.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-01-18 08:45:32 CET; 4s ago
  Process: 5106 ExecStop=/usr/local/bin/lxdui stop (code=exited, status=0/SUCCESS)
 Main PID: 5705 (lxdui)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/lxdui.service
           └─5705 /usr/bin/python3 /usr/local/bin/lxdui start

Jan 18 08:45:32 LXC-1 systemd[1]: Started Web UI for the native Linux container technology LXD/LXC.
Jan 18 08:45:32 LXC-1 lxdui[5705]: LXDUI ver. 2.1.2 -- (c)AdaptiveScale, Inc.
Jan 18 08:45:32 LXC-1 lxdui[5705]: http://www.adaptivescale.com
```
When launching lxdui like this, everyhting seems to work fine except the terminal, which doesd not display anything. black screen with blinking cursor.

When launching like : 
```
root@LXC-1:~# /usr/local/bin/lxdui start
LXDUI ver. 2.1.2 -- (c)AdaptiveScale, Inc.
http://www.adaptivescale.com
LXDUI started. Running on http://0.0.0.0:15151
PID=7912, Press CTRL+C to quit
```
Everything works fine.

Any idea about what's wrong ?
Regards

**Comment by chansdad** [comment]
I just faced this issue and resolved it . In my case , lxc was t 2.0.x version , updated it to 3.0.x

**Comment by vhajdari** [comment]
What's the version of LXD you are running?

**Comment by Rico29** [comment]
root@LXC-1:/# lxd --version
3.9

**Comment by Rico29** [comment]
hello
root@LXC-1:/# lxc version
Client version: 3.9
Server version: 3.9

**Comment by Rico29** [comment]
hello, any tip about this problem ?

**Comment by david-griffith** [comment]
Found a fix that works for me&trade;  - you need to specify the PATH environment variable in the lxdui.service file. Insert this line in the `[Service]` section :

`
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/snap/bin:/var/lib/snapd/snap/bin
`

I'm not entirely sure which path it actually requires - this was a straight copy of my PATH as root on my server, yours might be different, etc etc.

**Comment by Rico29** [comment]
Hello @david-griffith 
Thank you for the tip, it seems to fix the problem !

**Comment by joekrom** [comment]
hello @Rico29  i tried the same tips , but it did not work for me , When trying to open the terminal it is either black or i got sometimes cant create user data directory, permission denied. 
Any suggestion is pleased
