### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by 3xtr3m3d** [AdaptiveScale/lxdui#279]
Hi

I have installed lxdui on ubuntu 16.04 and i'm getting 500 internal server error message when trying to load ui.

here is the log 

> 2019-01-23 21:43.05 - tornado.application - ERROR - Uncaught exception GET /ui/ (112.135.86.228)
> HTTPServerRequest(protocol='http', host='51.68.189.148:15151', method='GET', uri='/ui/', version='HTTP/1.1', remote_ip='112.135.86.228')
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/tornado-5.0.2-py3.5-linux-x86_64.egg/tornado/web.py", line 1520, in _execute
>     result = self.prepare()
>   File "/usr/local/lib/python3.5/dist-packages/tornado-5.0.2-py3.5-linux-x86_64.egg/tornado/web.py", line 2826, in prepare
>     self.fallback(self.request)
>   File "/usr/local/lib/python3.5/dist-packages/tornado-5.0.2-py3.5-linux-x86_64.egg/tornado/wsgi.py", line 276, in __call__
>     WSGIContainer.environ(request), start_response)
>   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1978, in wsgi_app
>     ctx.push()
>   File "/usr/local/lib/python3.5/dist-packages/flask/ctx.py", line 332, in push
>     self.session = self.app.open_session(self.request)
>   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 912, in open_session
>     return self.session_interface.open_session(self, request)
>   File "/usr/local/lib/python3.5/dist-packages/flask/sessions.py", line 324, in open_session
>     s = self.get_signing_serializer(app)
>   File "/usr/local/lib/python3.5/dist-packages/flask/sessions.py", line 321, in get_signing_serializer
>     signer_kwargs=signer_kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/itsdangerous/serializer.py", line 95, in __init__
>     self.is_text_serializer = is_text_serializer(serializer)
>   File "/usr/local/lib/python3.5/dist-packages/itsdangerous/serializer.py", line 13, in is_text_serializer
>     return isinstance(serializer.dumps({}), text_type)
>   File "/usr/local/lib/python3.5/dist-packages/flask/sessions.py", line 85, in dumps
>     return json.dumps(_tag(value), separators=(',', ':'))
>   File "/usr/local/lib/python3.5/dist-packages/flask/json/__init__.py", line 177, in dumps
>     _dump_arg_defaults(kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/flask/json/__init__.py", line 98, in _dump_arg_defaults
>     bp.json_encoder if bp and bp.json_encoder
> AttributeError: 'Blueprint' object has no attribute 'json_encoder'
> 2019-01-23 21:43.05 - tornado.access - ERROR - 500 GET /ui/ (112.135.86.228) 5.75ms
> 2019-01-23 21:43.06 - tornado.access - INFO - 200 GET /favicon.ico (112.135.86.228) 7.33ms
> 2019-01-23 21:43.09 - tornado.access - INFO - 302 GET / (112.135.86.228) 5.77ms
> 2019-01-23 21:43.09 - tornado.application - ERROR - Uncaught exception GET /ui/ (112.135.86.228)
> HTTPServerRequest(protocol='http', host='51.68.189.148:15151', method='GET', uri='/ui/', version='HTTP/1.1', remote_ip='112.135.86.228')
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/tornado-5.0.2-py3.5-linux-x86_64.egg/tornado/web.py", line 1520, in _execute
>     result = self.prepare()
>   File "/usr/local/lib/python3.5/dist-packages/tornado-5.0.2-py3.5-linux-x86_64.egg/tornado/web.py", line 2826, in prepare
>     self.fallback(self.request)
>   File "/usr/local/lib/python3.5/dist-packages/tornado-5.0.2-py3.5-linux-x86_64.egg/tornado/wsgi.py", line 276, in __call__
>     WSGIContainer.environ(request), start_response)
>   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1978, in wsgi_app
>     ctx.push()
>   File "/usr/local/lib/python3.5/dist-packages/flask/ctx.py", line 332, in push
>     self.session = self.app.open_session(self.request)
>   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 912, in open_session
>     return self.session_interface.open_session(self, request)
>   File "/usr/local/lib/python3.5/dist-packages/flask/sessions.py", line 324, in open_session
>     s = self.get_signing_serializer(app)
>   File "/usr/local/lib/python3.5/dist-packages/flask/sessions.py", line 321, in get_signing_serializer
>     signer_kwargs=signer_kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/itsdangerous/serializer.py", line 95, in __init__
>     self.is_text_serializer = is_text_serializer(serializer)
>   File "/usr/local/lib/python3.5/dist-packages/itsdangerous/serializer.py", line 13, in is_text_serializer
>     return isinstance(serializer.dumps({}), text_type)
>   File "/usr/local/lib/python3.5/dist-packages/flask/sessions.py", line 85, in dumps
>     return json.dumps(_tag(value), separators=(',', ':'))
>   File "/usr/local/lib/python3.5/dist-packages/flask/json/__init__.py", line 177, in dumps
>     _dump_arg_defaults(kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/flask/json/__init__.py", line 98, in _dump_arg_defaults
>     bp.json_encoder if bp and bp.json_encoder
> AttributeError: 'Blueprint' object has no attribute 'json_encoder'
> 2019-01-23 21:43.09 - tornado.access - ERROR - 500 GET /ui/ (112.135.86.228) 5.45ms
> 2019-01-23 21:43.09 - tornado.access - INFO - 200 GET /favicon.ico (112.135.86.228) 5.30ms

can anyone help to fix this error?

Regards

**Comment by 3xtr3m3d** [comment]
never mind. reinstalled flask and it solved the problem

**Comment by vhajdari** [comment]
@3xtr3m3d , glad you were able to solve the problem.  Ok to close?

**Comment by vhajdari** [comment]
@3xtr3m3d, please make sure you change the default password, otherwise anyone will be able to connect to your instance and use it.

`lxdui init` or `python3 run.py init` -- this will prompt you for the user name and the password.

**Comment by 3xtr3m3d** [comment]
@vhajdari Thanks for the tip. changed password and yes please close
