### ISSUE TITLE
can lxdui access remote lxd ?

### ISSUE THREAD

**Issue by 3xtr3m3d** [AdaptiveScale/lxdui#280]
Can Lxdui access remote lxd?

we can add a remote lxd server and run command like 
`lxc list server-b:`
to view/access server-b containers from server-a.

if lxdui runs on server-a can lxdui list and manage server-b containers?

Regards

**Comment by vhajdari** [comment]
The functionality exists and the following PR ([252](https://github.com/AdaptiveScale/lxdui/pull/252)) provides a way to configure the setting in the conf file.  You can clone the develop branch and apply the PR if you want to test it.

**Comment by 3xtr3m3d** [comment]
@vhajdari Thanks. I will try that

**Comment by 3xtr3m3d** [comment]
@vhajdari i have did the way you mentioned. but i have no idea how to enable that function. tried adding line to the config but no idea how it works

**Comment by adietz00** [comment]
@vhajdari , I've followed your instructions to clone the dev branch, but I also don't know what to do next to be able to navigate to a remote LXD server. Could you provide some insight?

**Comment by vhajdari** [comment]
Hi @adietz00 

You need to update the following line `self.remoteHost = '127.0.0.1'` in 
```https://github.com/AdaptiveScale/lxdui/blob/master/app/api/models/LXCContainer.py``` to the remote host you are trying to use.

**Comment by nurely** [comment]
@3xtr3m3d @vhajdari What is the new way to handle this stuff? I have been trying hard to setup my url for remote LXD server. Please let me know :)

**Comment by ye-yng** [comment]
Would also be interested in an update. Changing the remoteHost value as specified by @vhajdari did not update the UI with the remote LXD's containers.

**Comment by nurely** [comment]
@ye-yng I did some changes, will try to refine it so that can be merged into master:

Change 1- https://github.com/nurely/lxdui/commit/ceae4ba9a1528b30874c3b0a791dc6ea18d8cb65
Change 2 - Inside the app/__metadata__.py --> add like here https://github.com/AdaptiveScale/lxdui/pull/252/files#diff-4bcf3c9def6ec7c4a73aa22228bcd784

Build again and it will work :D

**Comment by ye-yng** [comment]
@nurely Thanks for your help!
I am currently trying to access my Host machine's LXC containers from within an LXC container, by following your instructions I got a LXD not installed notification when accessing the UI. I will look further into the matter

**Comment by ye-yng** [comment]
Eventually I got it to a working state, on the `verify` attribute of Client do `verify=False` though unsafe it serves my purpose for now as it is only a container accessing my host machine.
