### ISSUE TITLE
error 500 when opening terminal of existing container

### ISSUE THREAD

**Issue by ghost** [AdaptiveScale/lxdui#281]
hi,

When i try to open a console on one of my existing containers i get an error 500. When i deploy a new container from lxdui en then try to open the console it works. Is this maybe a bug?

**Comment by vhajdari** [comment]
Hi @MichaelTrip1986 

Is this happening only for this one specific container, or is this problem encountered across containers?

**Comment by MichaelTrip** [comment]
Hi,

This my new acount. I appears on containers i converted from lxc to lxd.

**Comment by jetroni** [comment]
Hello @MichaelTrip, sorry for the very late reply, we are missing details regarding this bug and it's been a long time since this has been open. I am going to close this issue but please do re-open a new one if this still insists.
