### ISSUE TITLE
snapshot not working 

### ISSUE THREAD

**Issue by khokooli** [AdaptiveScale/lxdui#286]
snapshot not working for containers .... 
i can manually take snapshot whit : lxc snapshot command but cant whit web ui 
please help me to fix this problem ...

**Comment by vhajdari** [comment]
Hi @khokooli, you'll have to provide far more detail about your problem and your environment in order for anyone to be able to provide any assistance.

**Comment by xunge** [comment]
The same problems, and there are no debug informations in terminal, even use sudo command ...

**Comment by xunge** [comment]
I find that snapshot and clone are work well in Container's table actions. But when I click the container's name for details, the button of snapshot and clone's actions on the top are no response. Maybe it's a bug and hope for your reply~

**Comment by vinyll** [comment]
Same issue here.
When clicking on "snapshot" the popin appears.
Filling and saving won't do anything, the popin sticks there and no snapshot is created.

<img width="934" alt="Screenshot 2019-08-28 at 05 13 41" src="https://user-images.githubusercontent.com/145172/63823055-c6b89e80-c952-11e9-9599-b44c05f38689.png">

**Comment by ailegion** [comment]
@vinyll PR with a bugfix for this issue is already merged to develop branch and will be available in next release

**Comment by vinyll** [comment]
Great, thanks for the info; LXDUI is still an important part of my servers!
I'll move to that branch I guess.

**Comment by akanmanu** [comment]
It still not working. I'm on Ubuntu 18.04, my version of lxd is from the Ubuntu Backports
I click on it, but no response. no snapshot,no clone,no move,no export, no terminal.
i'm not using the version
![Screen Shot 2020-06-03 at 02 29 34](https://user-images.githubusercontent.com/3577707/83579822-fc725f80-a542-11ea-985c-73b458b0917a.png)

**Comment by akanmanu** [comment]
i did some update of my system, it works
