### ISSUE TITLE
lxdui config not working at all or need some adequate documentation

### ISSUE THREAD

**Issue by vlddm** [AdaptiveScale/lxdui#292]
```
root@z:~# lxdui config set port 11111
root@z:~# lxdui config set lxdui.port 11111
root@z:~# lxdui config show | head -n1
lxdui.port = 15151
```

**Comment by vhajdari** [comment]
Hi @vlddm ,

Which versions of LXD (snap or apt) and LXDUI are you experiencing the issue with?  Also, which version of Python 3?

**Comment by vlddm** [comment]
> Hi @vlddm ,
> 
> Which versions of LXD (snap or apt) and LXDUI are you experiencing the issue with? Also, which version of Python 3?

Python 3.6.9
lxdui master branch from github

**Comment by vhajdari** [comment]
Look like a bug.

**Comment by ailegion** [comment]
@vhajdari and @vlddm seems like a bug, I will look into this one and keep you updated

**Comment by jetroni** [comment]
Figured out that we were missing a save statement after setting it. Fixed.
