### ISSUE TITLE
Setup.py fails to run properly

### ISSUE THREAD

**Issue by ronlaws86** [AdaptiveScale/lxdui#303]
ubuntu@ubuntu:~/lxdui$ python3 setup.py 
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

**Comment by ronlaws86** [comment]
sudo apt-get install python3-setuptools 

-- Might be worth dropping in python dependancies on the readme, most ubuntu server installs come bare bones and lack a lot of packages.

- that being said. it failed here also. 
Installed /usr/local/lib/python3.6/dist-packages/pylxd-2.2.7-py3.6.egg
Searching for psutil==5.6.6
Reading https://pypi.python.org/simple/psutil/
Downloading https://files.pythonhosted.org/packages/5f/dc/edf6758183afc7591a16bd4b8a44d8eea80aca1327ea60161dd3bad9ad22/psutil-5.6.6.tar.gz#sha256=ad21281f7bd6c57578dd53913d2d44218e9e29fd25128d10ff7819ef16fa46e7
Best match: psutil 5.6.6
Processing psutil-5.6.6.tar.gz
Writing /tmp/easy_install-h0ys3l8o/psutil-5.6.6/setup.cfg
Running psutil-5.6.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-h0ys3l8o/psutil-5.6.6/egg-dist-tmp-7cn5wj__
psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

**Comment by ailegion** [comment]
@ronlaws86 can you please provide more details like what platform/OS you are using? I don't think we  encountered this issue before so any detail you can provide will be of great help.

**Comment by ghost81** [comment]
There is an error in app/__metadata__.py
The VERSION is still 2.1.2 instead 2.1.3

**Comment by ailegion** [comment]
@ghost81 there is fix on current develop branch - once the next release is available this issue should be resolved

**Comment by ronlaws86** [comment]
deleted old branch and re-ran a git pull and setup worked. was able to launch. 
However on both machines I did this on, (Ones AMD64 ones arm64) I get [This Issue now](https://github.com/AdaptiveScale/lxdui/issues/125) but that's not in the scope of this issue.
