### ISSUE TITLE
Prerequisites for installing LXDUI on Ubuntu/Fedora

### ISSUE THREAD

**Issue by prasadkumar013** [AdaptiveScale/lxdui#306]
Since the Wiki section has got information for configuring pre-requisites for Ubuntu, here are the packages I installed for installing LXDUI on Fedora 32. Couldn't find a way to open pull request for Wiki, so created as an issue.  Please point me in the right direction if this is not the place to do so.

------------------------------------------------------------------------------------------------------------------------------------
## Prerequisites

The following prerequisites are required to be installed on your system before you can install and use LXDUI.

#### 1) LXD
[LXD](https://linuxcontainers.org/) can be installed in one of three ways; from source, from the Ubuntu Backports or as a Snap package.  The recommended way is to use Snap package.

#### 2) Python 3
Version 2.0 of LXDUI is a complete rewrite based on [Python 3](https://www.python.org/downloads/), so please be keep in mind that all app related commands, if not specifically called out, will require that you have Python 3 installed on your system. 

#### 3) PIP (included in systems with Python 3.4 or higher)
[PIP](https://pip.pypa.io/en/stable/) is a package manager for Python applications.  In the event that a required package is missing from your system you can use PIP to install it.

#### 3) OpenSSL (libssl-dev on Ubuntu, openssl-devel on Fedora)
[OpenSSL](https://www.openssl.org/) is used for certificate management.

#### 4) ZFS
[ZFS](https://zfsonlinux.org/) is a combined file system and logical volume manager.  It's the preferred storage layer for LXD.

#### Virtualenv
[Virtualenv](https://virtualenv.pypa.io/en/stable/) is a tool to create isolated Python environments. Python “[Virtual Environments](https://packaging.python.org/tutorials/installing-packages/#creating-virtual-environments)” allow Python packages to be installed in an isolated location for a particular application, rather than being installed globally.

#### Fedora pre-requisites installation
`sudo dnf install git snapd openssl-devel python3 python3-pip python3-devel -y`
`sudo systemctl enable snapd && sudo systemctl start snapd`

#### Ubuntu pre-requisites installation
`sudo apt install -y git build-essential libssl-dev python3-venv python3-pip python3-dev zfsutils-linux bridge-utils`

##### Snap Installation
`sudo snap install lxd`

`lxd init`

Accept all the defaults for the prompts from `lxd init`.  For further instructions on installing and configuring LXD please refer to the following [link](https://linuxcontainers.org/lxd/getting-started-cli/).

### Install LXDUI
Follow the instructions located [here](https://github.com/AdaptiveScale/lxdui/wiki/Installing-LXDUI-2.0) to install LXDUI.

**Comment by ailegion** [comment]
@prasadkumar013 you can create a PR with README-FEDORA.md containing all this info. @mineibrm one the PR is merged go ahead and create section on wiki and link it on main wiki page

**Comment by prasadkumar013** [comment]
Created PR for instructions on setting up on Fedora 32.
