### ISSUE TITLE
Error 500 and log missing

### ISSUE THREAD

**Issue by Suzukaze-Aoba** [AdaptiveScale/lxdui#309]
I can't open teminal of a existing container(created outside UI) or a new container(created inside UI)
LXD download by apt
Python3
and nothing in lxdui/logs, i am confused

**Comment by Suzukaze-Aoba** [comment]
from pre issue,i see lxc set container image.os ubuntu .....
I tred that one,but there is no such key/value like image.os or image.release,also can't find them in https://linuxcontainers.org/lxd/docs/master/instances

**Comment by ailegion** [comment]
@mineibrm can you check this

**Comment by quantumchaos451** [comment]
Not sure if this helps re the opening a terminal but I was getting this when proxying through nginx. I need to add the headers:
```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
```
to get it to work.

**Comment by ailegion** [comment]
@quantumchaos451 glad you solved it. This issue more related to NGINX config to work with WS rather than LXDUI. After taking second look we made the decision that Terminal part of LXDUI requires rewrite based on new features provided by LXD.
