### ISSUE TITLE
VM creation in UIs

### ISSUE THREAD

**Issue by ye-yng** [AdaptiveScale/lxdui#321]
While I have seen this issue being posted before at https://github.com/AdaptiveScale/lxdui/issues/305, I was wondering if VM creation would be implemented in the future if LXD VMs are fully implemented?

**Comment by vhajdari** [comment]
We are in the process of rewriting the entire application from scratch, so
this would be the right time to consider it.  Contributions are welcome.

**Comment by jetroni** [comment]
#336
