### ISSUE TITLE
not working / unable to access web ui

### ISSUE THREAD

**Issue by eisengrau** [AdaptiveScale/lxdui#328]
Hello,

So I installed lxd and lxdui, seems like the default URL and port, which should be accessible from 0.0.0.0/1, I have http://172.21.4.4:15151, does not work. Tried setting a lower port, as I'm running this under root, but it seems like it does not work:

xdui config set lxdui.port 412

port still is 15151 which does not respond.

cheched with curl http://127.0.0.1:15151, it does give something:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/ui">/ui</a>.  If not click the link.root@brownbear:~/lxdui#

So the question is, what is the proper interface on which this responds. in this case when I do:

lxdui config show

I see some random value of IP which I did not set up:  lxd.ipv4.addr = 10.5.5.1 , is this the IP on which the web interface responds. currently this is in some sort of virtual lxc bridge(?). by default it should be the host's interface IP where the UI should respond, or...?

**Comment by vhajdari** [comment]
If you are on the same machine where lxd & lxdui are running you should be
able to hit http://127.0.0.1:15151 and that should load the UI.  Using a
port below 1024 will require that you run the process as root, so you
should avoid this.  If you want to set the port to a different number, say
8888, then update the lxdui.port parameter in lxdui.conf and restart the
service. By default the service will bind to all interfaces.

**Comment by eisengrau** [comment]
I'm so sorry. I had a temporary brain fart moment, or a n00b moment. iptables rules blocked any access from inside, even though ufw and firewalls were inactive on this host. Working now, thank you!
