### ISSUE TITLE
JWT token expired, unable to login

### ISSUE THREAD

**Issue by ye-yng** [AdaptiveScale/lxdui#334]
I have noticed an issue where at times after the JWT token expires it may lead to an infinite login loop as it uses the cached expired JWT instead of issuing a new one. This behaviour seems to be random as it doesn't always happen when the token expires. Clearing the browser cache is an easy fix for it, however it is not an ideal solution.

Anyone else with a similar issue can shine some light on the situation? Thank you.

**Comment by vhajdari** [comment]
Yes the JWT session timeout issue has been there for a while.  I saw that
you already submitted a PR for this issue so I guess this has now been
addressed.
