### ISSUE TITLE
[Security] Do not allow setting user passwords on the commandline

### ISSUE THREAD

**Issue by strugee** [AdaptiveScale/lxdui#341]
This is a security vulnerability because under an out-of-the-box Linux configuration, any user can read any process' command line arguments. That means that a local attacker would be able to see the new password as the command was being run.

To prevent this `lxdui user update` and friends should drop their `-p` option and instead only accept passwords interactively or via environment variable (environment variables are secure because they do not have the same problem, and they can be used in noninteractive settings just as easily).

**Comment by vhajdari** [comment]
Please submit a PR against the Development branch to add this functionality.
