### ISSUE TITLE
How do you change/add login ID and passwords?

### ISSUE THREAD

**Issue by bmullan** [AdaptiveScale/lxdui#87]
I installed this in Ubuntu 18.04 and at first couldn't find anywhere what the login ID & password were then I just tried admin/admin

Once logged in I didn't see any place to change that initial Login ID and Password or to add an additional account? 

I don't want to leave it on my system with a default admin/admin when it can access my containers?

Any pointers?

**Comment by vhajdari** [comment]
This is available via the CLI.  The documentation for the CLI is forthcoming, and will be finalized once the last few things are fully implemented.  By default we included the admin/admin account in the auth file, but you can change it when you initialize the app via:
`lui init`.  It will prompt you for a password that will be associated with the **admin** account.

To work with user accounts you have the following commands:
`lui user list`  -- Lists all configured users
`lui user add -u foo  -p secret` -- Creates a user name **foo** with password **secret**
`lui user --help` -- List of available commands for user management.

You can see what commands are available in the CLI with `lui --help`.  Each sub-command also has additional `--help` functionality.

**Comment by vhajdari** [comment]
Please refer to the CLI documentation on the wiki: [https://github.com/AdaptiveScale/lxdui/wiki/LXDUI's-CLI](url)

**Comment by bmullan** [comment]
thanks!

**Comment by pa314159** [comment]
Where can I find this CLI? I checked both master and devel and didn't find any reference to any "LUI".

The point is that I need to change the default admin password but I wasn't able to find a way...

**Comment by vhajdari** [comment]
`lui --> lxdui`  In 2.1 it was renamed to `lxdui` to conform to the snap packaging/naming convetions.
