### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by vg0426** [AdaptiveScale/lxdui#96]
Hi guys am getting this problem when trying to run the install, importerror no module named setuptools

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vhajdari** [comment]
Hi @vg0426 , 
What OS/version are you on?  Have you tried `sudo apt install python-setuptools`?

**Comment by Bierbox** [comment]
Hi, i'm having the same problem running the installation.
I'm getting the following error, although i installed python-setuptools:

```
someone:~/lxdui$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
```


My OS is Ubuntu 18.04 LTS
Do you know, how to solve this?

Thanks and greetings,
Bierbox

**Comment by vhajdari** [comment]
Most likely you don't have setuptools installed.  Try: `sudo apt install
python3-setuptools`

Did you set up the prerequisites?

**Comment by Bierbox** [comment]
Hi @vhajdari,

thank you for your answer.
I figured out for myself about 30 minutes ago :)

For Ubuntu 18.04, i had to install the following things as prequisite:
`apt-get install git libssl-dev python3-venv zfsutils-linux bridge-utils python-setuptools python3-setuptools python-dev build-essential libpython3.6-dev`

After that, the installation ended succesfully.

Thanks and greetings,
Bierbox

**Comment by vhajdari** [comment]
@Bierbox, I'm glad you were able to solve the problem.  Keep an eye out for 2.1.  We are releasing it this weekend.
